### ISSUE TITLE
Button is not working.

### ISSUE THREAD

**Issue by VeerSingh0001** [prashant-sehgal/Neutron#1]
<img width="960" alt="Screenshot 2023-07-24 115610" src="https://github.com/prashant-sehgal/Neutron/assets/115876530/7a8c22d7-6f87-40b8-9f39-79e5d91539da">  

Dear @prashant-sehgal   

The arrowed button is not working and nothing is happening on clicking it.   

Please tell this is bug or you put it only of show.    

Fell free to solve.

Thanks.😊

**Comment by prashant-sehgal** [comment]
that's a temporary button, only there to fill blank space.
Thanks' for downloading our application.
