### ISSUE TITLE
Shortcuts are got hidden.

### ISSUE THREAD

**Issue by VeerSingh0001** [prashant-sehgal/Neutron#2]
https://github.com/prashant-sehgal/Neutron/assets/115876530/76ace29e-d8d5-4f98-b4cf-9516b4e24695

Dear @prashant-sehgal   

In video I show that when we want to close the 1st tab than tab does not close but all the shortcuts get hidden and when we open a new tab after that than tab open normally but we can not close previous tab.  

Feel free to solve.  

Thanks.😊

**Comment by prashant-sehgal** [comment]
Thanks' for let us know about this issue.
It's V1 for Neutron Browser. This is just a Test Demonstration version of this software.
We are Gona rebuild this application in future using Electron and React.
Hopefully, this will be solved in that version.
If you found any working solution for this problem in this version, we invite you to contribute in this project...
